import { ArrowRight, BellRing, Check, ChevronRight, Clock3, FileText, MapPin, Plus, Search, SearchCheck, ShieldCheck, Sparkles } from "lucide-react";

const backpack = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=85";
const airpods = "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=85";

export default function Dashboard() {
  return <div className="dashboard-page shell-wide">
    <section className="dashboard-greeting"><div><div className="greeting-pills"><span className="eyebrow-pill"><span className="live-dot" />Live Campus Network</span><span className="help-pill"><span className="material-symbols-outlined">domain</span>Campus Help Desk: Open until 8:00 PM</span></div><h1>Good morning, Sidd.</h1><p>Welcome to your campus lost &amp; found hub. You have <strong className="blue-text">2 active reports</strong> and <strong className="violet-text">2 high-confidence matches</strong> awaiting your review.</p></div><div className="greeting-actions"><a className="button surface small" href="#matches"><BellRing size={17} className="violet-text" />Review Alerts (2)</a><a className="button primary small" href="/search"><Search size={17} />Browse Central Log</a></div><div className="dashboard-glow" /></section>
    <section className="metrics-grid"><Metric icon="radar" label="Active Lost Reports" value="2" state="Active" tone="amber" detail="Under active campus watch" /><Metric icon="inventory_2" label="Found Reports" value="1" state="Registered" tone="blue" detail="Logged with campus desk" /><Metric icon="auto_awesome" label="Potential Matches" value="3" state="2 New" tone="violet" detail="Awaiting student review" /><Metric icon="verified" label="Returned Items" value="4" state="Resolved" tone="green" detail="Successfully recovered" /></section>
    <section className="action-grid"><ActionCard tone="blue" title="Report Lost Item" copy="Misplaced something on campus? File a structured report immediately to alert campus reception desks and trigger matching." icon={<SearchCheck size={31} />} link="/report" foot="Notifies 14 department desks" /><ActionCard tone="green" title="Report Found Item" copy="Found something that belongs to a fellow student? Help get it back to them through the verified network." icon={<ShieldCheck size={31} />} link="/report" foot="Average handover: 2.4 hrs" /></section>
    <section className="dashboard-lower"><div className="panel reports-panel"><div className="panel-heading"><div><span className="section-eyebrow">YOUR ACTIVITY</span><h2>Recent reports</h2></div><a className="text-action" href="/search">View all <ArrowRight size={15} /></a></div><ReportRow image={backpack} title="Navy Herschel Backpack" meta="Reported lost · Central Library" status="Active · 2 days ago" tone="amber" /><ReportRow image={airpods} title="White AirPods Case" meta="Possible match found · North Quad" status="Match found · 4 hrs ago" tone="violet" /><ReportRow title="Black steel water bottle" meta="Reported found · Student Union" status="Returned · Sep 18" tone="green" icon="local_drink" /></div><div className="panel matches-panel" id="matches"><div className="panel-heading"><div><span className="section-eyebrow">AI ASSISTANCE</span><h2>Potential matches</h2></div><span className="match-count">2 new</span></div><MatchCard title="Navy Herschel Backpack" match="91% match" place="Central Library · 2nd Floor" /><MatchCard title="White AirPods Case" match="86% match" place="North Quad · Law Building" /><a className="button soft full-width" href="/search">Review all matches <ChevronRight size={16} /></a></div></section>
  </div>
}
function Metric({ icon, label, value, state, tone, detail }: { icon: string; label: string; value: string; state: string; tone: string; detail: string }) { return <div className="metric-card"><div className="metric-top"><span className={`metric-icon ${tone}`}><span className="material-symbols-outlined">{icon}</span></span><span className={`metric-state ${tone}`}>{state}</span></div><strong>{value}</strong><b>{label}</b><span>{detail}</span></div> }
function ActionCard({ tone, title, copy, icon, link, foot }: { tone: string; title: string; copy: string; icon: React.ReactNode; link: string; foot: string }) { return <article className={`action-card ${tone}`}><div><span className="action-kicker">FAST INTAKE · 2 MIN</span><div className="action-card-main"><div><h2>{title}</h2><p>{copy}</p></div><span className="action-big-icon">{icon}</span></div></div><div className="action-card-footer"><span><Clock3 size={15} />{foot}</span><a className="button action-button" href={link}>Start report <ArrowRight size={15} /></a></div></article> }
function ReportRow({ image, title, meta, status, tone, icon }: { image?: string; title: string; meta: string; status: string; tone: string; icon?: string }) { return <div className="report-row">{image ? <img src={image} alt="" /> : <div className="report-placeholder"><span className="material-symbols-outlined">{icon}</span></div>}<div className="report-row-copy"><strong>{title}</strong><span>{meta}</span><small><i className={`status-dot ${tone}`} />{status}</small></div><ChevronRight size={17} className="muted-icon" /></div> }
function MatchCard({ title, match, place }: { title: string; match: string; place: string }) { return <div className="match-card"><div className="match-card-top"><span className="match-spark"><Sparkles size={15} /></span><strong>{match}</strong></div><b>{title}</b><span><MapPin size={13} />{place}</span><a href="/search">Review match <ArrowRight size={14} /></a></div> }
