import { CheckCircle2, ChevronDown, ImagePlus, MapPin, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { PublicHeader } from "../App";

export default function ReportItem() {
  const [mode, setMode] = useState<'lost' | 'found'>('lost');
  const [submitted, setSubmitted] = useState(false);
  const [color, setColor] = useState('Blue');
  return <div className="public-page"><PublicHeader /><main className="report-main"><div className="report-shell">
    {submitted && <div className="success-banner"><div className="success-symbol"><CheckCircle2 size={18} /></div><div><strong>Report #LR-2024-89 submitted successfully</strong><span>Campus help desks and security dispatch have been alerted in real time.</span></div><button onClick={() => setSubmitted(false)} aria-label="Dismiss"><X size={17} /></button></div>}
    <div className="report-topline"><a href="/dashboard" className="back-link"><span className="material-symbols-outlined">arrow_back</span>Back to Dashboard</a><span className="secure-label"><span className="live-dot" />Secure Protocol 4.2</span></div>
    <section className="report-heading-card"><div><span className="section-eyebrow"><span className="material-symbols-outlined">edit_document</span>STANDARD INTAKE PROTOCOL</span><h1>Report an Item</h1><p>Provide accurate details to help campus staff and students identify the item and accelerate secure reclamation.</p></div><div className="segmented"><button className={mode === 'lost' ? 'active' : ''} onClick={() => setMode('lost')}><span />Report Lost Item</button><button className={mode === 'found' ? 'active' : ''} onClick={() => setMode('found')}><span />Report Found Item</button></div></section>
    <section className="progress-card"><div><strong>Step 1 of 3:</strong><b>Item Information &amp; Distinctive Attributes</b><span>Step 2: Custody &amp; Retrieval → Step 3: Match Verification</span></div><div className="progress-track"><i /><i /><i /></div></section>
    <form className="intake-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>
      <section className="form-card"><FormCardHeader icon="category" title="General Identification" label="Required" /><div className="form-grid"><Field label="Item Name" required help="Use clear generic titles rather than brand names alone."><input required placeholder="e.g., Black Laptop, Blue Backpack, AirPods Case" /></Field><Field label="Category" required help="Assigns the listing to appropriate intake filters."><div className="select-wrap"><select required defaultValue=""><option value="" disabled>Select category...</option><option>Electronics &amp; Laptops</option><option>Bags &amp; Wallets</option><option>Student ID &amp; Cards</option><option>Keys &amp; Badges</option><option>Bottles &amp; Containers</option><option>Books &amp; Notebooks</option></select><ChevronDown size={18} /></div></Field><Field label="Brand & Model Reference" help="Leave blank if maker marks are not visible."><input placeholder="e.g., Apple MacBook Air M2, Herschel Little America" /></Field><div className="field"><label>Primary Color</label><div className="color-pills">{['Black', 'Blue', 'Silver/Grey', 'Red', 'Green'].map((c) => <button type="button" key={c} onClick={() => setColor(c)} className={color === c ? 'active' : ''}><i className={`color-dot ${c.toLowerCase().split('/')[0]}`} />{c}</button>)}</div><small>Choose the closest visible colour.</small></div></div></section>
      <section className="form-card"><FormCardHeader icon="pin_drop" title={mode === 'lost' ? 'Location & Timing' : 'Found Location & Timing'} label="Required" /><div className="form-grid"><Field label={mode === 'lost' ? 'Last Seen Location' : 'Found Location'} required><div className="select-wrap"><select required defaultValue=""><option value="" disabled>Select a campus location...</option><option>Central Library</option><option>Student Union</option><option>North Quad</option><option>Engineering Wing</option><option>Sports Complex</option></select><ChevronDown size={18} /></div></Field><Field label={mode === 'lost' ? 'Approximate Time Lost' : 'Approximate Time Found'} required><input required type="datetime-local" /></Field><Field label="Distinctive Features" full help="Keep one private detail for ownership verification."><textarea rows={3} placeholder="Scratches, stickers, engravings, case details, or other identifying features" /></Field></div></section>
      <section className="form-card"><FormCardHeader icon="photo_camera" title="Photo & Additional Details" label="Optional" /><div className="upload-box"><ImagePlus size={23} /><strong>Drag an image here, or <u>browse files</u></strong><span>PNG, JPG or WEBP · Max 10MB</span><input type="file" accept="image/*" /></div><div className="field"><label>Additional Details</label><textarea rows={3} placeholder="Anything else that could help the campus recovery network?" /></div><div className="privacy-note"><ShieldCheck size={18} /><span><strong>Privacy-first reporting</strong> Do not share your phone number, serial number, or private ownership evidence in the public description. Keep one identifying detail private for verification.</span></div></section>
      <div className="form-actions"><a className="button surface" href="/dashboard">Cancel</a><button className="button primary" type="submit">Submit {mode === 'lost' ? 'Lost' : 'Found'} Report <span className="material-symbols-outlined">arrow_forward</span></button></div>
    </form>
  </div></main></div>
}
function FormCardHeader({ icon, title, label }: { icon: string; title: string; label: string }) { return <div className="form-card-header"><div><span className="material-symbols-outlined blue-text">{icon}</span><h2>{title}</h2></div><span className="required-label">{label}</span></div> }
function Field({ label, required, help, full, children }: { label: string; required?: boolean; help?: string; full?: boolean; children: React.ReactNode }) { return <div className={`field ${full ? 'full' : ''}`}><label>{label}{required && <em> *</em>}</label>{children}{help && <small>{help}</small>}</div> }
